"""create_keycloak_users_table

Revision ID: bf82bf1a16b2
Revises: c47170969a2e
Create Date: 2025-08-01 14:04:03.245995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'bf82bf1a16b2'
down_revision: Union[str, Sequence[str], None] = 'c47170969a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keycloak_users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('keycloak_user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('reset_code', sa.String(), nullable=True),
    sa.Column('reset_code_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('keycloak_user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_keycloak_users_id'), 'keycloak_users', ['id'], unique=False)
    op.create_index(op.f('ix_keycloak_users_email'), 'keycloak_users', ['email'], unique=True)
    op.create_index(op.f('ix_keycloak_users_keycloak_user_id'), 'keycloak_users', ['keycloak_user_id'], unique=True)
    op.create_index(op.f('ix_keycloak_users_username'), 'keycloak_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keycloak_users_username'), table_name='keycloak_users')
    op.drop_index(op.f('ix_keycloak_users_keycloak_user_id'), table_name='keycloak_users')
    op.drop_index(op.f('ix_keycloak_users_email'), table_name='keycloak_users')
    op.drop_index(op.f('ix_keycloak_users_id'), table_name='keycloak_users')
    op.drop_table('keycloak_users')
    # ### end Alembic commands ###
